deps:
	ansible-galaxy install stwind.erlang --force
	ansible-galaxy install angstwad.docker_ubuntu --force
	ansible-galaxy install Ansibles.erlang --force
	ansible-galaxy install Ansibles.build-essential --force
	ansible-galaxy install zzet.rbenv --force
