{application,starter,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib,lager,sasl,poolboy,exec]},
              {mod,{starter_app,[]}},
              {env,[{pools,[{default,[{size,10},{max_overflow,5}],[]}]}]},
              {modules,[langs,starter,starter_app,starter_pool,starter_sup,
                        starter_worker]}]}.
